AMREX_HOME ?= ../../subprojects/amrex

TOP = ../..

COMP     = gnu
USE_MPI  = FALSE
USE_OMP  = FALSE

PRECISION = DOUBLE
DEBUG     = FALSE

DIM      = 3
NO_HYDRO = TRUE

Bpack := ./Make.package
Blocs := .

include $(TOP)/Exec/Make.Nyx
